import { roboto } from "@/font";
import "@/style/globals.css";
import Provider from "@/app/ui/Provider";
import Header from "@/app/ui/Header";
import Footer from "@/app/ui/Footer";
import { AppProvider } from "@/app/ui/AppContext";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider>
        <body className={`${roboto.className} antialiased`}>
          <AppProvider>
            <Header />
            <ToastContainer position="top-center" />
            {children}
            <Footer />
          </AppProvider>
        </body>
      </Provider>
    </html>
  );
}
