import { inter } from '@/font';
import '@/style/globals.css';
import Provider from '@/components/Provider';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { AppProvider } from '@/components/AppContext';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <Provider>
        <body className={`${inter.className}`}>
          <AppProvider>
            <Header />
            {children}
            <Footer />
          </AppProvider>
        </body>
      </Provider>
    </html>
  );
}
