<<<<<<< HEAD
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@/utils/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
=======
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
>>>>>>> 2c1918b3506d3d91c9e25a67ea6489082eefbef0
};

export default function RootLayout({ children }) {
  return (
<<<<<<< HEAD
    <html lang="en">
      <Provider>
        <body className={inter.className}>{children}</body>
      </Provider>
=======
    <html lang='en'>
      <body className={inter.className}>{children}</body>
>>>>>>> 2c1918b3506d3d91c9e25a67ea6489082eefbef0
    </html>
  );
}
