import SideMenu from "@/components/SideMenu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function ProductLayout({ children }) {
  return (
    <div className="flex items-start">
      <SideMenu />
      {children}
    </div>
  );
}
